"""TraceRook documentation, derived from MVP1/MVP2 specifications and acceptance evidence.

Sections contain authored HTML. No user input or remote source is rendered here.
"""
from html import escape

PAGES = []

def page(slug, title, group, description, *sections):
    PAGES.append(dict(slug=slug, title=title, group=group, description=description, sections=sections))

def table(headers, rows):
    return '<div class="table-wrap"><table><thead><tr>' + ''.join('<th scope="col">'+escape(h)+'</th>' for h in headers) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join('<td>'+escape(c)+'</td>' for c in row)+'</tr>' for row in rows) + '</tbody></table></div>'

def code(text):
    return '<div class="code-wrap"><pre><code>'+escape(text)+'</code></pre><button class="copy-code" type="button" aria-label="Copy code example">Copy</button></div>'

def note(text):
    return '<div class="callout"><p>'+text+'</p></div>'

page('introduction', 'Meet TraceRook', 'Start here', 'An independent review layer for supported local coding-agent actions.',
('purpose','A second look before execution','''<p>Coding agents can edit files, execute commands, contact services, and read instructions from sources you did not author. TraceRook is designed to add an independent review layer that relates a proposed action to the task you actually asked the agent to perform.</p><p>The MVP2 architecture extends the native preview and combines deterministic local policy with Anthropic Claude for contextual analysis. It focuses on supported local Claude Code and Codex sessions on one Mac. A native menu bar companion keeps status visible; a SwiftUI dashboard explains findings and presents one-time reviews.</p>'''),
('current','What you can try today','''<p>The current development milestone includes the native interface, deterministic Cloud Demo fixtures, sample incident evidence, and a sample approval experience. MVP2.0 adds strict IPC v2 contracts, exact invocation bindings, and helper codec self-tests while preserving v1 compatibility. The local suite has 43 passing tests.</p><p>Live hook ingestion, the background service transport, safe hook installation, actual enforcement, SQLite persistence, and direct Anthropic BYOK are pending. The app does not claim verified real protection. A polished sample screen is a demonstration of the interaction, not proof of interception.</p><p>Start with <a href="/docs/quickstart/">the native preview</a>, then read <a href="/docs/roadmap/">the implementation status</a>.</p>'''),
('model','The intended decision model',table(['Risk','MVP1 response','Authority'],[
('Critical','Immediate denial with concrete local evidence','Enabled catastrophic deterministic rule'),('High','Pause for human review; expiry denies','Local evidence or contextual recommendation'),('Medium','Allow with warning and finding','Deduplicated advisory decision'),('Low','Allow with minimal event record','No TraceRook override of host permissions')])+'''<p>Claude can recommend review and identify drift. It cannot grant permissions or erase a deterministic critical denial. TraceRook Allow Once only releases its own gate; the coding agent’s native permissions still apply.</p>'''),
('boundaries','Know the boundary','''<p>TraceRook is a hook-based guardrail. It is not a system-wide sandbox or an endpoint detection platform. A hook that never runs cannot enforce a denial. An intercepted shell call can start nested processes that TraceRook does not separately mediate.</p><p>Remote sessions, hosted tool paths without local callbacks, arbitrary commands outside an integrated agent, and tampering by another process with the same user privileges are outside the complete guarantee. See <a href="/docs/coverage/">coverage and failure behavior</a>.</p>'''),
('requirements','Platform and product scope','''<ul><li>Apple Silicon Mac with macOS 26 or later.</li><li>Swift 6, SwiftUI, and the macOS 27 SDK for development.</li><li>Individual developer, local hook-capable Claude Code and Codex sessions.</li><li>Developer ID signed and notarized distribution is a release gate; the current source build is a development preview.</li></ul><p>OpenCode, enterprise management, a real TraceRook Cloud backend, billing, and vulnerability scanning are deferred beyond MVP1.</p>'''))

page('quickstart', 'Try the native preview', 'Start here', 'Build the development app and explore a complete, explicitly labeled sample workflow.',
('requirements','Before you build','''<p>Use an Apple Silicon Mac running macOS 26 or later, with Swift 6 and the macOS 27 SDK. Full Xcode 27 is required for Xcode archives. The repository also includes a Command Line Tools build path used for local validation.</p><p>This guide runs the current UI and fixture milestone. It does not install agent hooks, register a Login Item, collect an Anthropic key, or enable live protection.</p>'''),
('build','Build from source',code('./scripts/build.sh\nopen build/TraceRook.app')+'''<p>Run these commands from the root of the current TraceRook development checkout. They require the native application source and scripts; the static website by itself is not an app source distribution. You can also open <code>TraceRook.xcodeproj</code> and select the TraceRook scheme. Development builds are ad-hoc signed unless a signing identity is supplied. Signature integrity alone does not establish Developer ID trust or notarization.</p><p>There is no signed release download available in this milestone. Review the repository’s <a href="/reference/SECURITY_LIMITATIONS.md">security limitations</a> before using a source build.</p>'''),
('demo','Explore Cloud Demo',code('open build/TraceRook.app --args --demo')+'''<ol><li>Open Overview and confirm the Demo label.</li><li>Browse Sessions and select a sample session to inspect its task context and timeline.</li><li>Open Incidents and inspect the evidence, policy reference, response, and execution certainty.</li><li>Select Simulate review, then open Approvals or the native review panel.</li><li>Choose Block or Allow once before the sample’s 45-second deadline. An expired response is rejected.</li></ol><p>The sample account, usage, and plan screens use bundled fixtures. No cloud enrollment, purchase, or analysis request occurs.</p>'''),
('real','Check the real activity view','''<p>Switch away from the sample view. Real activity should stay empty and integrations should show Not integrated or an unchecked state. Installing Claude Code or Codex on your Mac does not make the development app a live security gate.</p><p>BYOK remains unavailable; its live implementation is planned for MVP2.5. Do not manually wire the foundation hook executable into your agent configuration: its normal operational path is intentionally unsupported.</p>'''),
('checks','Run the local checks',code('./scripts/smoke-test.sh\n./scripts/ui-smoke-test.sh')+'''<p>The smoke script compiles the three executables, runs the Swift Testing harness, and exercises harmless fixture demonstrations. The UI script produces native light and dark render artifacts. These checks do not prove real-host enforcement or a notarized release.</p><p>For the full distinction between current evidence and release gates, read <a href="/docs/testing/">testing and verification</a>.</p>'''))

page('dashboard', 'Navigate the dashboard', 'Start here', 'Use the native interface to understand sessions, evidence, reviews, and integration health.',
('overview','Overview and menu bar','''<p>Overview summarizes the selected data source, recent findings, pending reviews, and integration coverage. The current demo uses seeded fixtures. Actual coverage remains visibly separate from sample findings.</p><p>The native menu bar is the quick entry point into the dashboard and pending approvals. The MVP1 design requires its state to follow real service and integration health, rather than showing a permanently green shield. Closing a dashboard window and stopping background protection are distinct operations once the background service is implemented.</p>'''),
('sessions','Sessions and timelines','''<p>A session ties activity to a provider, the host’s session identifier, and a subagent identifier when one exists. Its task anchor records a concise, redacted summary of the user’s intent. If the task is unavailable, the UI must say Task unknown.</p><p>A timeline should let you connect a proposal to local evidence, review, and observed execution. Sessions sharing the same repository are not automatically one session. A post-tool event describes an action that already happened.</p>'''),
('incidents','Read an incident','''<p>Each finding should answer four questions: what was attempted, what evidence raised concern, how the action related to the task, and what TraceRook did. Rule IDs and contextual rationale explain the decision; a score is a routing aid, not proof of malicious intent.</p><p>Keep execution certainty separate from the policy outcome. Allowed by TraceRook does not mean the host executed the call. An asynchronous drift finding cannot retroactively prevent earlier work.</p><p>Demo incidents use sample evidence. They do not describe current activity on your Mac.</p>'''),
('reviews','Approvals and native review','''<p>The review panel presents one pending action, its agent, task relevance, evidence, and deadline. Allow once and Block are bound to that exact pending invocation. A stale notification must open an expired state rather than provide permission for a new attempt.</p><figure class="review-figure"><img src="/assets/app-review.png" alt="Native TraceRook pending approval panel with sample evidence and Allow once and Block controls" width="1360" height="1560" loading="lazy"><figcaption>Actual native review panel · sample approval</figcaption></figure><p>Read <a href="/docs/approvals/">the approval state machine</a> for the intended live guarantees.</p>'''),
('settings','Integrations and settings','''<p>Integrations shows installation, trust, version compatibility, and verification as separate facts. Settings includes provider selection, appearance, notification authorization, privacy previews, and explicitly simulated Cloud Account, Usage, and Plans.</p><p>Enabling notification permission is an explicit user action. Notifications may be suppressed by Focus or system settings; the approvals queue remains necessary. The current build does not accept an API key or install integrations.</p>'''))

page('cloud-demo', 'Cloud Demo', 'Start here', 'Explore bundled sample data without mistaking a demonstration for real protection.',
('fixtures','What Demo contains','''<p>Cloud Demo is a finished-looking product walkthrough backed exclusively by local fixture JSON. It includes a sample account, plan, usage values, sessions, incidents, and an interactive sample review.</p><p>Sample identities and statistics are synthetic. The dashboard and affected views identify them as Demo or sample data. The demo exists to make the native interaction testable before real integrations are available.</p>'''),
('network','No analysis network requests','''<p>The demo provider and mock cloud API client read bundled resources and make no outbound requests. There is no TraceRook Cloud authentication, billing, metering, subscription, or production analysis backend in MVP1.</p><p>The public product website is also static. It never reads agent sessions, performs Claude analysis, or accepts API keys. Hosting access controls are separate from the native app’s Cloud Demo.</p>'''),
('isolation','Keep real activity separate','''<p>A real session must never be passed to the fixture provider and reported as analyzed by Cloud. The intended live behavior when Demo mode is selected is local deterministic rules only for real sessions, with a clear provider indicator.</p><p>In the current development milestone, live ingestion and enforcement are not connected at all. Real sessions remain empty and Not integrated. Selecting a sample provider is not a way to enable protection.</p>'''),
('sample-review','Try a sample review','''<p>Simulate review creates a local synthetic pending action. Try Block, try Allow once on a fresh sample, and let another request expire. The sample exercise demonstrates terminal transitions and late-response rejection, without issuing a dangerous command.</p><p>The fixture flow does not test a real host waiting on a hook. That requires the separate MVP2 live-host acceptance gates.</p>'''),
('future','The future Cloud contract','''<p>The architecture separates the analysis provider from the cloud account API. A future HTTPS implementation can replace the mock behind its protocol, but a future-facing data model is not an operational service.</p><p>The provisional API includes device registration, account, usage, plans, analysis, and incidents. Real auth, billing, account enrollment, and subscriptions are deferred. See <a href="/docs/protocols/">protocol reference</a> for the contract boundary.</p>'''))

page('how-it-works', 'The decision pipeline', 'Policy & protection', 'Follow a supported proposal from local inspection to a host-format decision.',
('intercept','1. A host hook presents the proposal','''<p>A compatible, configured, enabled, and trusted local agent runs a PreToolUse command hook. The signed TraceRook bridge reads the host’s JSON, applies bounded parsing, and sends a deadline-bound request to the per-user background service.</p><p>This point is the enforcement opportunity. PostToolUse is useful for observation but comes after execution. A host path that skips or fails to launch the hook cannot be blocked by this pipeline.</p>'''),
('inspect','2. Inspect the original action locally','''<p>The policy engine derives command shape, sensitive-path references, intended network destinations, mutation scope, and task-related features in memory. It evaluates correlated evidence rather than treating every appearance of a command token as malicious.</p><p>Concrete catastrophic evidence yields an immediate deterministic denial. A routine cleanup inside disposable build output must not inherit the same decision as destructive changes outside the repository.</p>'''),
('claude','3. Ask Claude only when context is useful','''<p>Suspicious or ambiguous proposals may use direct Anthropic BYOK analysis after minimization, redaction, consent, and a second privacy preflight. The request contains a task anchor and selected event summaries rather than a full transcript.</p><p>Claude’s verdict is advisory and strictly validated. A model-only critical label routes to high-risk human review. An outage, malformed response, exhausted budget, or unsafe payload falls back to the local decision with an accurate provider status.</p>'''),
('human','4. Bind review to the pending call','''<p>A high-risk decision persists a pending request with an exact action fingerprint and expiry. The native app receives the event through authenticated XPC. The user can allow once or deny; the service rejects stale, mismatched, repeated, or disconnected responses.</p><p>A default 45-second approval window sits within the outer host timeout, targeted at 75 seconds and subject to real-host verification. If a high-risk pending request expires, the callback returns a denial.</p>'''),
('return','5. Return to the host and retain certainty','''<p>The bridge translates the decision into the host’s supported output. No TraceRook override uses empty stdout and a successful exit, preserving native agent permissions. A denial uses a validated host-compatible response.</p><p>The record distinguishes interception, blocking before execution, permission past TraceRook, observed execution, and execution unknown. The current development build exercises fixtures only; this live sequence remains a release gate.</p>'''))

page('rules', 'Local policy & rule families', 'Policy & protection', 'Understand deterministic evidence, severity routing, and the role of contextual analysis.',
('families','The MVP1 rule taxonomy',table(['Rule ID','Evidence or purpose','Default response'],[
('TR-CRED-EXFIL','Sensitive credential path + outbound transfer in the same effective command','Critical denial'),('TR-SENSITIVE-READ','Unusual read of SSH, cloud, Keychain, or token locations','High review if unrelated'),('TR-DESTRUCT-OUTSIDE','Recursive destruction targeting home, system, or outside the repository','Critical denial'),('TR-SECURITY-CONFIG','Security controls, authentication, or persistence changes','High / critical'),('TR-REMOTE-EXEC','Fetch-and-execute from an external destination','High review'),('TR-PRIV-ESC','Privilege or permission expansion; privileged mutation','High review'),('TR-UNKNOWN-EGRESS','New outbound destination with sensitive inputs','High review'),('TR-PUBLISH-DEPLOY','Publish, force-push, release, deploy, or production mutation','High when task mismatches'),('TR-DOTENV-ACCESS','Sensitive environment/token access outside the task','Medium / high'),('TR-POLICY-TAMPER','Verified disabling or alteration of app-owned safeguards','Critical when verified'),('TR-ENCODED-COMMAND','Obfuscation combined with a high-impact operation','High review'),('TR-REPEAT-DENIED','A repeated previously denied action','High + drift review'),('TR-REPO-INSTRUCTION','Untrusted instructions attempting to redirect intent','Asynchronous medium / high'),('TR-TASK-DRIFT','Aggregate behavior inconsistent with the task anchor','Asynchronous medium / high')])+'''<p>These are planned MVP2 policy requirements, not a claim that the current demo has a live detector.</p>'''),
('severity','Scores explain routing',table(['Range','Severity','Policy'],[('0–39','Low','Allow and minimally record'),('40–69','Medium','Allow and notify'),('70–89','High','Human review'),('90–100','Critical','Requires concrete catastrophic deterministic evidence')])+'''<p>Review and warning thresholds default to 70 and 40. Automatic critical blocking depends on an individually enabled catastrophic rule, not a configurable numeric threshold alone. A risk score is neither a probability of attack nor a measured security efficacy percentage.</p>'''),
('precedence','Evidence has precedence','''<ol><li>Protection disabled means no new TraceRook policy decisions and an explicit off status.</li><li>A trusted catastrophic deterministic match denies immediately.</li><li>An exact, scoped, unexpired exception can release a non-catastrophic action.</li><li>Deterministic high-risk evidence requests review.</li><li>A contextual model recommendation with evidence can request review or warn.</li><li>Medium risk warns while allowing; low risk records with no override.</li></ol><p>The model cannot lower a deterministic critical denial. A quick Allow once control must not create a catastrophic exception. Such an exception would require a separate deliberate advanced-settings flow.</p>'''),
('parsing','Conservative command interpretation','''<p>Rules must consider paths, quoting, redirection, pipelines, embedded interpreter flags, normalized relative components, and known symlinks when safe. A regex is not a shell sandbox. Ambiguous high-impact commands should move to review rather than receive a silent safe classification.</p><p>Generic build cleanup, disposable workspace operations, and legitimate dependency work need benign near-miss tests. Correlated features and task scope matter: a sensitive path alone is insufficient evidence for the same denial as a credential upload.</p>'''),
('behavior','Unsafe actions and agent behavior','''<p>Unsafe-action findings focus on the proposed operation. Agent-behavior findings focus on task drift, prompt injection, repeated overrides, or suspicious delegation. A finding can belong to both categories.</p><p>Asynchronous review can influence future risk posture and warn about drift, but cannot undo an earlier action. Task unknown should reduce drift confidence. All findings should retain evidence and explain limitations.</p>'''))

page('approvals', 'One-time approvals', 'Policy & protection', 'A review decision authorizes one exact pending invocation, within its deadline.',
('binding','What Allow once means','''<p>Allow once permits the exact waiting tool call past TraceRook’s review gate. It does not authorize the session, approve similar future commands, skip the host’s own permissions, or prove execution.</p><p>The fingerprint binds provider, session, turn when available, source tool-call ID, tool name, working directory, and canonical original input. When the host lacks a call identifier, a local invocation nonce distinguishes attempts. A redacted summary or command substring is not sufficient authorization.</p>'''),
('states','Terminal state is written once',table(['State','Meaning'],[('pending','Waiting on a live, bound invocation before its deadline'),('approved_once','The exact pending invocation was released past TraceRook'),('denied','The pending invocation was denied'),('expired','The review deadline passed; high-risk request denies'),('aborted','The invocation was invalidated by disconnect, end, or mismatch')])+'''<p>A transaction or compare-and-set operation must accept at most one terminal transition. Double-clicks, notification replays, and simultaneous UI responses cannot create multiple permissions.</p>'''),
('deadlines','Deadlines and disconnects','''<p>The default approval window is 45 seconds from the pre-tool event, bounded by the host callback deadline. The proposed outer hook timeout is 75 seconds; exact versions and behavior must be verified on real hosts.</p><p>Disconnecting the bridge, ending the session, expiring the invocation, or changing its fingerprint invalidates the request. A late approval cannot release a later retry. Expired UI must show No longer pending and disable live approval controls.</p>'''),
('notifications','Notifications are entry points','''<p>A native notification offers Review and, where supported, Block. Review opens the focused detail panel. Critical denials offer details rather than a quick in-flight allow. Notification text must omit full commands, credentials, source, and private repository names.</p><p>Focus mode or denied permissions can prevent delivery. The menu bar and approvals queue remain mandatory; the service must resolve the deadline even if the user never sees a notification or the UI exits.</p>'''),
('current','Try the sample state machine','''<p>The current app supports a synthetic review with a 45-second deadline, terminal-response rejection, and a native panel. This local sample is useful for the interaction and foundation tests.</p><p>Authenticated service mutations, durable transitions, bridge disconnect handling, and real-host waiting calls remain MVP2.1–MVP2.4 acceptance work. Read <a href="/docs/quickstart/">the preview guide</a> to try the sample safely.</p>'''))

page('coverage', 'Coverage & failure behavior', 'Policy & protection', 'Verified protection requires a working callback, a supported tool path, and real evidence.',
('verified','What must be verified','''<p>A protected decision requires a supported local session; configured, enabled, trusted hooks; receipt of the event by TraceRook; a tool path that honors a pre-execution denial; and a compatible adapter that passed schema and smoke checks.</p><p>A config file on disk is not proof the host runs it. An installed executable is not proof it is trusted. A heartbeat is useful, but a real pre-tool blocking test is needed for each claimed tool class.</p>'''),
('labels','Status language and its meaning',table(['Label','Meaning'],[('Protected (verified hooks)','The relevant local callback and blocking path have actual verification evidence'),('Monitoring only','Events observed; blocking for the tool class has not been validated'),('Degraded','Service, provider, hook, or configuration errors reduce verified capability'),('Not integrated','No validated integration connects the session'),('Demo data','Entirely synthetic sample content')])+'''<p>Keep provider health separate from hook health. Anthropic unavailable can mean Local rules only; it does not automatically mean every local callback failed. Idle sessions should show Verification not recent rather than being declared broken solely for inactivity.</p>'''),
('callback-failure','When the callback runs but a dependency fails','''<p>The MVP1 bridge must contain the same lightweight catastrophic fallback rules as the service. If the service or provider is unreachable after the bridge actually starts, matched critical signatures can still return a valid denial before the host’s timeout.</p><p>The default outage policy allows low or unknown activity with degraded status and denies clearly sensitive mutation or exfiltration signatures. Strict offline protection can optionally deny all mutable or executable tool classes during an outage. This guarantee exists only inside a callback that runs and finishes in time.</p>'''),
('lost-hook','When the hook never completes','''<p>If the host skips the hook, cannot launch it, or times it out, TraceRook cannot force a block. Both hosts can continue after hook errors or timeouts. Config checks, missing helpers, detected failures, and stale heartbeats must surface coverage limitations when detectable.</p><p>A preference labeled fail closed cannot make a missing callback enforce policy. Same-user processes can alter configurations or execute outside the integration. TraceRook is not tamper-proof against the user account.</p>'''),
('tool-boundaries','Paths outside the local guarantee','''<ul><li>Hosted or remote actions without compatible local callbacks.</li><li>Codex hosted WebSearch and specialized paths that bypass local hooks.</li><li>Codex <code>write_stdin</code> continuation, which does not necessarily create a new pre-tool gate.</li><li>Nested commands, processes, and network activity inside an already allowed shell call.</li><li>Manual terminal commands and applications outside an integrated agent.</li></ul><p>Post-tool observations do not undo execution. TraceRook cannot promise complete exfiltration prevention, system-wide process control, or universal sandboxing.</p>'''),
('current','Current preview coverage','''<p>The development app has no live integration. Its real activity is Not integrated and sample findings are Demo data. Signed IPC, real callbacks, fallback enforcement, and both hosts’ pre-execution proofs remain pending.</p><p>Coverage claims will be version-specific. An agent newer than the verified range must show Compatibility not yet verified until validation is complete.</p>'''))

page('claude-analysis', 'Analysis with Anthropic Claude', 'Claude & privacy', 'The planned contextual analysis backend: direct Anthropic BYOK, minimized context, and advisory verdicts.',
('role','Why Claude is in the pipeline','''<p>TraceRook’s contextual analysis backend is designed around Anthropic Claude. Deterministic local rules handle concrete dangerous signatures; Claude assesses ambiguous action intent, task relevance, prompt injection indicators, and cumulative agent drift.</p><p>This is distinct from Claude Code as an integrated coding agent. A Codex session can also receive contextual analysis from Claude. TraceRook owns its policy and review flow; the analysis model supplies a bounded risk report.</p><p>Live Anthropic integration is MVP2.5 work. The current native preview and this static website make no Claude analysis requests.</p>'''),
('connection','Bring your own key, connect directly','''<p>The intended provider uses URLSession over TLS to send requests directly to Anthropic’s Messages API at <code>https://api.anthropic.com/v1/messages</code>. The key is retrieved just in time from macOS Keychain. There is no TraceRook analysis proxy, shared vendor account, browser OAuth, or website key form.</p><p>Choose a supported, configurable Claude model identifier and API version based on actual provider compatibility. TraceRook must not invent a future model name or claim universal structured-output support. If structured output is unavailable for the selected model, strict JSON decoding and conservative failure handling are required.</p><p>External reference: <a href="https://platform.claude.com/docs/en/api/overview">Anthropic API overview</a>.</p>'''),
('payload','What context is selected','''<ul><li>A concise, locally redacted task anchor derived from user prompts.</li><li>A sanitized description of the proposed action and local policy matches.</li><li>Relevant recent sanitized event summaries from a bounded rolling context, approximately 20 events.</li><li>Recent denials, unusual target/path changes, and untrusted instruction indicators when observed.</li><li>Redaction counts, evidence, and confidence limitations.</li></ul><p>No full transcript or repository tree is automatically sent. Additional code excerpts default off and require explicit opt-in to bounded selected lines. A separate minimal remote payload is checked again immediately before transmission.</p>'''),
('authority','Claude does not grant permissions','''<p>The system prompt defines a read-only security analyst. Inspected content is encoded as untrusted data. The model returns a versioned, constrained JSON verdict with enumerated categories and actions, bounded strings and arrays, a valid confidence range, evidence, and limitations.</p><p>The app must reject unexpected execution requests or policy text. Model-only critical findings are capped at high-risk review; Claude cannot silently hard-block solely by attaching a critical label. Concrete deterministic critical evidence cannot be downgraded.</p>'''),
('timing','Deadlines, budgets, and availability','''<p>MVP2 allocates an 8-second internal model deadline, separate from the 45-second human review window and approximately 80-second bridge cap. Host timeout settings still need installed-version verification. These are engineering limits, not guaranteed network latency. Retries for rate limits or server errors use bounded jitter only while the hard deadline permits.</p><p>Defaults are 30 synchronous model calls and 12 drift checks per session, plus a configurable daily budget. When paused or exhausted, local rules continue and the UI says AI analysis paused — local rules active. Estimated costs must be labeled as estimates based on returned tokens and configured price data.</p>'''),
('consent','Consent and provider retention','''<p>First-run BYOK consent must explain that selected redacted context goes directly to Anthropic and redaction cannot guarantee removal of every secret. Show a readable payload preview. Validation, replacement, and deletion of the key are distinct operations; saved keys are never redisplayed in full.</p><p>Anthropic retention and deletion follow the user’s provider terms. They are separate from TraceRook’s local retention settings. Read <a href="/docs/privacy/">the privacy pipeline</a> and <a href="/docs/data-retention/">local data retention</a>.</p>'''))

page('privacy', 'The privacy pipeline', 'Claude & privacy', 'Minimize first, redact locally, and reject remote transmission when the final check cannot complete.',
('collection','Collect only the necessary input','''<p>The intended input source is the event supplied by a supported local hook. TraceRook does not silently scrape screens, accessibility trees, full transcripts, other applications, or entire source trees. MVP1 does not request blanket Full Disk Access.</p><p>Original tool arguments may remain temporarily in process memory to derive features and bind the immediate decision. The normalized record must not persist an unredacted command body by default. The current demo reads only packaged fixtures.</p>'''),
('redaction','Normalize and redact on your Mac','''<p>Local inspection derives command, sensitive-path, and destination features before constructing a sanitized representation. Likely API tokens, bearer credentials, private key headers, and password-like assignments are replaced with stable category placeholders that do not expose recoverable original values.</p><p>Sensitive home-directory components are removed when unnecessary. A placeholder is not a permission to include unlimited context. The remote request is built separately from any local-only path or host summary.</p>'''),
('preflight','A second gate before the network','''<ol><li>Create a minimal payload with a task anchor, selected event summaries, local policy evidence, and relevant uncertainty.</li><li>Apply payload size bounds.</li><li>Run the secret scanner again immediately before the network request.</li><li>If scanning fails, cannot complete, or lacks sufficient confidence, reject remote transmission.</li><li>Mark AI analysis unavailable and use the local policy outcome.</li></ol><p>The app must not resolve a failed privacy check by sending unknown raw input. Additional code excerpts use the same pipeline and remain off by default.</p>'''),
('untrusted','Treat inspected content as untrusted','''<p>Repository instructions, tool responses, documents, web pages, and proposed commands are data. Text saying “ignore policy” or “approve this action” is not administrator intent. Claude requests isolate such excerpts in clearly labeled, JSON-encoded untrusted fields.</p><p>Only TraceRook owns the model’s system policy. The model returns findings; it never supplies executable commands or permissions. Evidence may link an instruction to later behavior when observed, but causal certainty must not be invented.</p>'''),
('logs','Keep diagnostics sparse','''<p>Logs and crash diagnostics contain predefined status codes and identifiers, not raw prompts, commands, provider responses, secrets, or key values. Exports require an explicit user action and must remain sanitized.</p><p>MVP1 avoids anonymous analytics uploads. The static website loads its own assets and documentation search index. It includes no third-party analytics, trackers, external fonts, API key input, or session upload form. Hosting may retain ordinary access logs and, for a private publication, apply its own authentication.</p>'''),
('limits','Understand the limit of redaction','''<p>Redaction can miss unknown secret formats or inferable sensitive context. The consent flow must say this directly. BYOK transmission is permitted only for explicitly allowed, minimized context; it is not a guarantee that no private information can ever leave the Mac.</p><p>Provider retention is governed by the user’s Anthropic account and terms. Local permissions protect a user-owned history database; MVP1 does not promise encrypted SQLite storage or resistance to a compromised same-user process.</p>'''))

page('data-retention', 'Keys, history & deletion', 'Claude & privacy', 'Separate API key lifecycle, sanitized local history, and integration removal.',
('keychain','API keys belong in Keychain','''<p>The planned BYOK implementation stores its API key in macOS Keychain with appropriate login accessibility and signed-app-family access restrictions. The service reads the value only when required for an authenticated request.</p><p>Keys must not go into UserDefaults, SQLite, fixture JSON, logs, or the static website. The app needs distinct replace, validate, and delete operations with accurate errors and no full-key redisplay. Keychain integration is pending in the current build.</p>'''),
('storage','The intended local store','''<p>The per-user service is the sole SQLite writer. Its database path is <code>~/Library/Application Support/TraceRook/data/tracerook.sqlite</code>, with a <code>0700</code> parent directory and <code>0600</code> database file.</p><p>Use WAL, prepared statements, foreign keys, migrations, indexes, and transactional approval updates. Session identities must handle nullable subagent IDs correctly: a plain nullable UNIQUE key can permit duplicate logical sessions.</p><p>MVP1 relies on macOS file permissions and minimization. Database encryption is a future consideration, not a current claim.</p>'''),
('retention','Default retention',table(['Data','Default','Notes'],[('Sanitized event summaries','14 days','Daily purge; shorter user settings permitted'),('Incidents and approvals','30 days','Keep explanations and decision audit'),('Session records','Until references expire','Remove after retained events/incidents are gone'),('API key','Until user deletes or replaces it','Keychain; independent from history'),('Raw tool JSON / transcripts','Do not persist by default','Temporary decision memory only')])+'''<p>Durable retention and purge are pending MVP2.1 functionality. The current fixture experience is not a live activity archive.</p>'''),
('deletion','Three separate operations','''<ul><li><strong>Delete All Local History:</strong> remove retained session, event, finding, and approval records under a defined safe operation.</li><li><strong>Delete API Key:</strong> remove the Keychain credential and make BYOK unavailable.</li><li><strong>Uninstall Integrations:</strong> remove only TraceRook-owned hook entries and optionally unregister the helper.</li></ul><p>Uninstalling an integration must not silently erase history or another agent’s settings. Deleting history must not imply deleting data Anthropic already received.</p>'''),
('cloud','Cloud and diagnostics','''<p>Cloud Demo account and usage data are bundled samples. No real enrollment, billing record, or cloud history exists. Diagnostics exports are local and sanitized unless the user explicitly chooses a destination.</p><p>Local history settings and provider terms are separate privacy boundaries. See <a href="/docs/claude-analysis/">Anthropic consent and analysis</a> and <a href="/docs/safe-installation/">safe uninstall behavior</a>.</p>'''))

page('claude-code', 'Claude Code integration', 'Agent integrations', 'The intended local hook lifecycle and verification requirements for Claude Code.',
('scope','Supported integration scope','''<p>MVP1 targets local Claude Code sessions with compatible user hooks, including local CLI and IDE-embedded sessions where those callbacks actually execute. The host can offer other execution environments; TraceRook’s local guarantee does not extend to them automatically.</p><p>The current adapter normalizes sanitized schema fixtures and encodes fixture decisions. It does not install or run a live integration. Do not manually install the foundation bridge as an operational security hook.</p>'''),
('configuration','Consent-based hook configuration','''<p>The intended installer modifies <code>~/.claude/settings.json</code> only after a readable before/after preview and explicit consent. It preserves unrelated keys, matchers, and hooks, creates a permission-preserving backup, and refuses a write if the source changed.</p><p>Required lifecycle hooks include SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, and SessionEnd. PostToolUseFailure is optional. InstructionsLoaded can inform behavioral context, but is not itself an enforcement gate.</p>'''),
('decisions','Pre-tool decisions','''<p>PreToolUse is the hook that can deny a supported proposal before execution. TraceRook’s no-override path exits successfully with empty stdout, leaving Claude Code’s native permission flow intact.</p><p>A denial uses validated <code>hookSpecificOutput.permissionDecision = "deny"</code> or exit code <code>2</code> with sanitized stderr. Debugging text must never contaminate stdout. High-risk human review waits synchronously within the callback before returning its final host-compatible result.</p><p>External reference: <a href="https://code.claude.com/docs/en/hooks">Claude Code hooks reference</a>.</p>'''),
('verification','Installation is only the first check','''<p>Verification needs the exact detected host version, adapter version, schema check, configuration state, helper signature, successful callback, and real pre-tool blocking evidence. Policy may disable user hooks even when a file contains them.</p><p>Onboarding must exercise a harmless real host call and show its receipt. A separate harmless blocked fixture must prove the body never ran. Newer-than-verified versions show Compatibility not yet verified.</p>'''),
('failure','Failure and repair','''<p>A callback error or timeout can let execution continue. If the bridge starts but the service is unavailable, shared local fallback rules can return a timely denial for known catastrophic evidence. A hook that does not run cannot enforce it.</p><p>Repair must preserve unrelated settings and use the same consent and optimistic-concurrency protections as installation. App moves must not silently rewrite user configurations. See <a href="/docs/safe-installation/">safe configuration changes</a>.</p>'''))

page('codex', 'Codex integration', 'Agent integrations', 'Local hook coverage, explicit trust review, and host-compatible decision output.',
('scope','Local function-tool coverage','''<p>MVP1 targets compatible local Codex sessions. Shell calls map to Bash in the hook matcher. Supported local apply_patch, function, and MCP tool paths can provide pre-tool callbacks; hosted tools and some specialized paths are outside the default boundary.</p><p>The fixture adapter exists in the current source build. Live installation, event ingestion, and enforcement are pending.</p>'''),
('configuration','Hook sources and user trust','''<p>The intended user-level integration preserves <code>~/.codex/hooks.json</code> or the active configuration representation supported by the installed host. Existing JSON and TOML hooks must remain intact; do not replace the user’s configuration wholesale.</p><p>Nonmanaged Codex hooks require explicit review and trust. A newly installed or changed hook definition may be skipped until trusted. Onboarding must guide the user through <code>/hooks</code>, then verify actual execution. TraceRook does not bypass host trust.</p><p>External reference: <a href="https://developers.openai.com/codex/hooks">Codex hooks reference</a>.</p>'''),
('output','Return only supported decisions','''<p>The specification requires validated <code>hookSpecificOutput.permissionDecision = "deny"</code> for denial and empty successful output for no TraceRook override. Human review waits inside the synchronous command hook.</p><p>Do not implement a review hold with <code>permissionDecision: "ask"</code>, <code>continue: false</code>, or an unsupported field combination. The host can treat invalid pre-tool output as a failed hook and continue the call. Exact behavior must be tested against the detected release.</p>'''),
('continuations','A continuation is not a new gate','''<p>Codex <code>write_stdin</code> sends input to or polls an existing unified-exec session. It does not necessarily run PreToolUse again. Later input and nested activity cannot be presented as independently intercepted tool calls without actual evidence.</p><p>Hosted WebSearch does not use the local function-tool hook path, and specialized tools can opt out. PostToolUse may arrive when the original command finishes; that is observation after execution.</p>'''),
('verification','What enables a verified status','''<p>Record installation, trust, version, adapter schema, actual callback receipt, pre-tool test time, and host-specific coverage notes. Installed and untrusted is Needs trust, not Protected.</p><p>Acceptance requires a harmless deny test proving the body never ran, high-risk Block and Allow once paths with native host permissions preserved, expiry rejection, and failure-state checks. Until then, the current app shows real activity as Not integrated.</p>'''))

page('safe-installation', 'Safe configuration changes', 'Agent integrations', 'Reversible, consent-based hook installation, repair, and removal are part of the security boundary.',
('preview','Plan before modifying','''<p>The installer detects supported user configuration locations and versions without recursive full-disk scanning. It builds a concrete change plan showing the exact before/after content, affected files, owned hook entries, and backup locations.</p><p>The user chooses integrations and explicitly consents. TraceRook must not alter managed corporate policies, silently disable other hooks, or treat executable discovery alone as support verification.</p>'''),
('backup','Backups and source-hash checks','''<p>Create timestamped, permission-preserving backups in an app-owned directory before modification. Preserve unknown fields and unrelated hooks in meaning. Parsing and targeted changes must respect the actual JSON or TOML structure.</p><p>Hash the original source used for the preview. If it changes before the write, abort and create a fresh plan. This optimistic-concurrency guard prevents overwriting a user’s intervening edit or another installer’s change.</p>'''),
('atomic','Verify and write atomically','''<ol><li>Verify the signed bridge and its version before wiring a hook.</li><li>Copy it by verified, atomic replacement to a stable user path.</li><li>Write the modified configuration to a temporary file in the same directory.</li><li>Synchronize and rename atomically, retaining intended permissions.</li><li>Validate parsing and host support after the change.</li><li>Verify an actual callback and blocking behavior before claiming coverage.</li></ol><p>Stable bridge path: <code>~/Library/Application Support/TraceRook/bin/tracerook-hook</code>. Host shell-form commands use an absolute, correctly quoted path.</p>'''),
('ownership','Idempotent ownership and repair','''<p>TraceRook tracks its own hooks with a stable command/argument fingerprint or a schema-permitted marker. It must not add unrecognized properties just to mark ownership. Reinstalling should not duplicate handlers.</p><p>Monitor hashes, missing helpers, disabled hooks, trust, and callbacks. If repair is needed after an update or app move, show the change plan again. Codex may need renewed human trust for changed definitions.</p>'''),
('uninstall','Remove only owned entries','''<p>Uninstall removes TraceRook-owned entries and leaves unrelated settings and hooks. Restore an old full file only when there are no structural conflicts; a backup must not overwrite newer user changes.</p><p>Helper registration, history retention, and Keychain deletion are independent choices. All work remains user-level and nonprivileged; MVP1 does not require root or sudo. Safe Claude Code and Codex installation is planned for MVP2.2 and MVP2.3.</p>'''))

page('troubleshooting', 'Troubleshooting', 'Agent integrations', 'Diagnose demo, provider, notification, trust, and coverage states without overstating protection.',
('empty','Real activity is empty','''<p>This is expected in the current development preview. Use Explore Demo or launch with <code>--demo</code> to browse sample activity. The foundation service and bridge expose self-tests but do not provide operational live ingestion.</p><p>Do not change host settings to make the preview appear integrated. Read <a href="/docs/roadmap/">the roadmap</a> for the next live acceptance gate.</p>'''),
('byok','Anthropic BYOK is unavailable','''<p>The current build does not accept API keys or make provider requests. MVP2.5 will add Keychain, consent, validation, budgets, and real analysis.</p><p>In the intended live build, a revoked key, network outage, rate limit, unsafe payload, or exhausted budget leaves local rules available with accurate provider status. Replacing a key must not be mistaken for verifying agent hook coverage.</p>'''),
('notification','A review notification did not appear','''<p>Check TraceRook’s notification permission in system settings and consider Focus mode. Permission should be requested only through an explicit app action. The native sample review remains accessible through Approvals.</p><p>The intended service must expire high-risk reviews safely even if delivery fails, the app is not running, or the user never opens the panel. An old notification cannot authorize a later action.</p>'''),
('trust','An integration is installed but not verified','''<p>In a future live build, distinguish configuration, helper availability, host trust, adapter compatibility, callback receipt, and blocking tests. Codex requires user review of nonmanaged hooks via <code>/hooks</code>. No trust-bypass flag is part of TraceRook setup.</p><p>Do not reset or replace entire agent settings to repair one hook. Use a fresh, explicit configuration plan. If a session is idle, verification age may be stale without implying failure.</p>'''),
('build','A source build fails','''<p>Confirm Apple Silicon, macOS 26+, Swift 6, and the macOS 27 SDK. Use the checked-in build and test scripts for Command Line Tools environments; Xcode archive validation needs full Xcode.</p><p>Known local adjustments include SwiftPM’s native build backend and an SDK 27 State-wrapper compatibility alias when the Command Line Tools installation lacks the macro plugin. These are documented development-tool observations, not waived release requirements.</p>'''),
('report','Useful diagnostic details','''<p>A report should include the app and host versions, status code, adapter version, configuration state, trust state, whether a real callback was observed, and sanitized reproduction steps. Never include keys, raw hook payloads, full transcripts, or private source.</p><p>Use the <a href="https://github.com/kleprevost/tracerook">source repository</a> to inspect the current implementation record. Local sanitized diagnostic export is an upcoming live feature.</p>'''))

page('mvp2', 'What shipped in MVP2.0', 'Engineering reference', 'A tested foundation for real protection, with a clear boundary between working contracts and future integrations.',
('shipped','The foundation is complete','''<p>MVP2.0 is the first implementation phase of the real-protection plan. It preserves the native SwiftUI app and synthetic Cloud Demo while adding strict versioned IPC contracts. It is a development preview, not an active security gate for your real sessions.</p><p>The local suite now has 43 passing tests: the original 23 plus 20 security contract tests. All three executables compile in debug and optimized configurations. Bundle relocation, resource failure, native launch and 20 light/dark render cases pass.</p><p>These checks validate software behavior in this phase. No real-host denial or real Anthropic analysis has been demonstrated yet, and the app correctly keeps real activity Not integrated.</p>'''),
('contracts','What the new contracts enforce','''<p>IPC v2 uses explicit length-prefixed JSON, byte/depth/string/cardinality limits, strict typed fields and duplicate-key rejection before decoding. Decimal precision survives original-input canonicalization. Unknown versions, ambiguous input, malformed frames and mismatched reply IDs are rejected.</p><p>Each invocation gets a fresh 128-bit nonce generated by the operating system. Review messages bind the provider, session, event, tool call, action fingerprint, nonce and request identity. Demo-origin requests and critical quick-allow review messages cannot enter this live review contract.</p><p>A hook reply can only deny or impose no additional override. It cannot grant native permissions, rewrite the action or assert execution. Binding checks are working code; caller authentication, service-owned expiry and atomic approval consumption still need implementation.</p><p>See <a href="/docs/protocols/">the v2 protocol reference</a> for exact bounds and preserved v1 compatibility.</p>'''),
('try','Try the safe helper demonstration',code('''./scripts/build.sh
build/TraceRook.app/Contents/MacOS/tracerook-hook --protocol-version
build/TraceRook.app/Contents/MacOS/tracerook-hook --self-test
build/TraceRook.app/Contents/MacOS/TraceRookAgent --self-test''')+'''<p>The protocol command prints 2. The hook self-test validates a synthetic adapter fixture and an in-memory v2 request/reply round trip. The service self-test validates bundled fixtures and budget framing. Neither command starts a listener, installs an integration or grants host permissions.</p><p>Continue to explore the native sample review with <a href="/docs/quickstart/">the preview guide</a>. Do not install this foundation bridge into agent settings as a live hook; its operational path remains disabled.</p>'''),
('evidence','Installed hosts are not verified coverage','''<p>The read-only audit found Claude Code 2.1.290 and Codex 0.162.0-alpha.2 on the development Mac. Those versions have not passed a TraceRook live deny test. No tool class is marked Protected, and detecting a binary is not proof that its hooks run.</p><p>Future evidence must identify exact versions, adapter and binary identity, tool class and an actual harmless deny with an absent canary side effect. Hook trust, native permissions, skipped callbacks and timeout behavior remain independent constraints.</p><p>The next PR implements authenticated service IPC, SQLite and real UI state. Safe host installation and actual callbacks follow after that security boundary exists. Real Anthropic BYOK is a separate MVP2.5 milestone.</p>'''),
('references','Read the authoritative records','''<ul><li><a href="/reference/TraceRook_MVP2_Architecture_Implementation_Spec.md">MVP2 architecture and implementation specification</a></li><li><a href="/reference/TraceRook_MVP2_Agent_Handoff.md">Implementation handoff and PR sequence</a></li><li><a href="/reference/docs/MVP2_ACCEPTANCE.md">Phase-by-phase acceptance matrix</a></li><li><a href="/reference/docs/MVP2_PR2_PLAN.md">Concrete PR2 service and IPC plan</a></li><li><a href="/reference/docs/IMPLEMENTATION_STATUS.md">Actual build, test and platform evidence</a></li></ul><p>Read <a href="/docs/roadmap/">the release roadmap</a> for the remaining gates. Real analysis, verified blocking, signed distribution and accessibility need their own evidence before a protection beta can ship.</p>'''))

page('architecture', 'Native architecture', 'Engineering reference', 'Three native processes, shared Swift packages, and separate authenticated UI and event transports.',
('processes','Process responsibilities',table(['Process','Responsibility'],[('TraceRook.app','SwiftUI dashboard, MenuBarExtra, onboarding, UserNotifications, native review, settings'),('TraceRookAgent','Per-user nonprivileged LaunchAgent: policy, model scheduling, approval deadlines, SQLite, health'),('tracerook-hook','Signed arm64 CLI: bounded stdin, socket request, host output, shared catastrophic fallback')])+'''<p>The app uses Swift 6 and standard Apple frameworks. There is no Electron or web view shell. The planned service registration uses a supported per-user mechanism with explicit consent. No service is registered in this milestone and no root daemon is part of the design.</p>'''),
('flow','How the components connect','''<div class="architecture-flow"><ol><li><strong>Claude Code / Codex</strong>A supported local lifecycle hook provides host JSON.</li><li><strong>Signed bridge</strong>Length-prefixed JSON travels over a user-owned Unix socket.</li><li><strong>Agent service</strong>Normalize, inspect, redact, classify, and bind the exact action.</li><li><strong>Policy and provider</strong>Local rules first; permitted selected context goes directly to Anthropic when needed.</li><li><strong>Approval and native UI</strong>Authenticated XPC publishes status and accepts authorized review mutations.</li><li><strong>Host decision and history</strong>Return a host-compatible result; retain a sanitized, uncertainty-aware audit record.</li></ol></div>'''),
('modules','Shared modules and concurrency','''<p>Contracts own versioned envelopes, enums, and provider-independent representations. AgentAdapters own host names and input/output mapping. Privacy owns redaction and minimization. Rules and Core own deterministic evidence, evaluation precedence, and state transitions.</p><p>Mutable stores, review coordination, analysis scheduling, and health monitors use actors. UI state is MainActor-isolated. Async/await carries deadlines and cancellation. The service alone writes SQLite; the UI reads through XPC rather than opening the live database concurrently.</p>'''),
('boundaries','Trust and transport boundaries','''<p>Input and model reasoning are untrusted. The planned CLI event socket must check kernel peer credentials and bound every frame. The tested v2 codec is implemented; an operating socket and peer authentication are not. Same-user malicious interference remains a coverage limit. Approval and trust mutations belong exclusively on an authenticated signed-client XPC endpoint.</p><p>UI peers require audit-token/code-signature validation against the intended signed family. The CLI socket must never accept approve or trust operations. This split is an explicit MVP2.1 prerequisite for live review.</p>'''),
('layout','Repository layout',code('App/                         Native SwiftUI + AppKit where needed\nAgent/                       Background service executable\nHookCLI/                     Signed command-line bridge\nPackages/TraceRookContracts/  Versioned contracts\nPackages/TraceRookCore/       Provider and approval foundations\nPackages/TraceRookPrivacy/    Sanitization utilities\nPackages/TraceRookAgentAdapters/\nPackages/TraceRookFixtures/   Explicit demo resources\nTests/                       Swift Testing harness\nResources/                   Icon, Info.plist, LaunchAgent plist\nwebsite/                     Static product site and docs')+'''<p>The source milestone has executable foundations and native demo functionality. Service transport, durable history, safe installation, live rule enforcement, and Keychain-backed analysis remain pending. See <a href="/docs/roadmap/">the acceptance record</a>.</p>'''))

page('protocols', 'Events & IPC contracts', 'Engineering reference', 'Versioned bounded input, normalized event envelopes, exact fingerprints, and host output.',
('events','Normalized event v1',code('''{
  "schema_version": 1,
  "event_id": "sample-event-id",
  "agent": "claude_code",
  "source_session_id": "sample-session-id",
  "agent_sub_id": null,
  "source_turn_id": null,
  "source_tool_call_id": "sample-tool-call-id",
  "kind": "pre_tool_use",
  "occurred_at": "2026-10-08T12:00:00Z",
  "cwd": "/Users/dev/projects/widget",
  "repo_root": "/Users/dev/projects/widget",
  "tool_name": "Bash",
  "action_type": "shell_exec",
  "args_summary": "Proposed outbound transfer referencing a credential",
  "risk_features": ["sensitive_file_reference", "outbound_upload"],
  "redaction_count": 2,
  "raw_input_truncated": false,
  "action_fingerprint": "sha256-of-canonical-original-action",
  "metadata": {"host_permission_mode": "default"}
}''')+'''<p>This is a sanitized illustrative envelope, not an accepted live request. Supported event kinds are session_start, user_prompt, pre_tool_use, post_tool_use, post_tool_failure, session_end, and instruction_loaded. Action types include shell_exec, file_read, file_write, file_edit, network, mcp, subagent, and other.</p>'''),
('transport','Live IPC v2 contracts','''<p>MVP2.0 implements the additive v2 codec and DTOs. It does not start a socket listener. The planned Unix endpoint has a private <code>0700</code> directory and <code>0600</code> socket; real peer checks and transport cancellation are MVP2.1 work.</p><p>A frame is a four-byte network-order length followed by exactly one JSON payload. Bounds are 1 MiB per request, 16 KiB per reply, depth 32, 64 KiB of encoded string content, 1,024 members per object, and 2,048 elements per array. Duplicate decoded keys, unexpected typed fields, invalid UTF-8, unknown versions and unsupported precision are rejected.</p><p>The v2 request carries protocol_version, request_id, request_kind, adapter, adapter_version, received_at_ms, hard_deadline_ms, host_version, invocation_nonce and host_payload. Original host input stays transient; it must never be copied into logs, SQLite or a remote request.</p><p>Replies carry a matching request_id and only <code>no_override</code> or <code>deny</code>, plus a bounded reason, explanation, optional incident ID, decision source and tool class. <code>execution_observed</code> is always <code>unknown</code>. No override preserves host permissions; it is not an execution grant.</p><p>The codec checks a 100 ms default monotonic decode deadline. Checks around Foundation are cooperative rather than preemptive. Runtime waits, read deadlines, peer identity and request deduplication still require service implementation. Legacy event schema v1 and fixture readers remain unchanged.</p>'''),
('fingerprints','Exact action binding','''<p>Canonical SHA-256 input contains provider, session, optional turn, tool-call ID, tool name, working directory, and original tool input. MVP2 requires a fresh 128-bit system-random invocation nonce even when the host provides a call ID. Include subagent identity in the approval’s exact scope and isolate simultaneous sessions.</p><p>The digest uses original input, not a model-generated title or redacted command summary. Foundation numeric parsing rejects values outside supported exact decimal bounds rather than allowing distinct originals to round to the same action representation.</p><p>A fingerprint binds the observed invocation. It does not grant cryptographic control over later nested processes or transport continuations.</p>'''),
('ui','Authenticated UI mutations','''<p>The planned native control plane uses NSXPCConnection to a signed endpoint; it is not active in this build. Approval and trust mutations require validated peer audit tokens and code-signing identity. Such mutations must not be exposed on the CLI’s UID-checked event socket.</p><p>Approval state changes must verify exact binding, pending state, deadline, and invocation liveness, then commit one terminal transition. An event observation channel is not an authorization channel.</p>'''),
('providers','Provider verdict contract','''<p>AnalysisProvider offers availability and deadline-bound analysis with explicit modes: anthropicBYOK, traceRookCloudDemo, and localRulesOnly. A model verdict contains schema version, category, severity, confidence, suspicious flag, rationale, evidence, recommended action, drift, and limitations.</p><p>Production decoding enumerates values, caps lengths, rejects additional properties, validates confidence, and refuses execution instructions. The demo provider only accepts demo-origin requests; it cannot truthfully analyze a real session.</p>'''),
('future-cloud','Provisional Cloud API','''<p>CloudAPIClient has a fixture implementation in MVP1. Future account, device-registration, usage, plans, analysis, and incident routes are provisional versioned contracts. They are not endpoints implemented by this static site or by a real TraceRook Cloud service.</p><p>No auth, login, enrollment, billing, or subscription behavior is implied by a sample account screen.</p>'''))

page('testing', 'Testing & verification', 'Engineering reference', 'Compilation and fixtures are necessary; real pre-execution behavior is a separate acceptance gate.',
('local','Current local evidence','''<p>The implementation record dated October 8, 2026 reports debug and release builds of all three arm64 executables with Swift 6 and SDK 27, plus 43 passing Swift Testing cases (23 retained tests and 20 new security contract tests). Native rendering checks cover 20 light/dark cases, including demo/real separation, pending/expired review, and denied notifications.</p><p>Scene launch and relocated bundle checks validate a visible dashboard and packaged resources. Full Xcode archive validation, manual VoiceOver coverage, and actual notification delivery acceptance remain pending. These are development results, not efficacy claims.</p>'''),
('commands','Run the relevant checks',code('./scripts/test.sh\n./scripts/smoke-test.sh\n./scripts/bundle-smoke-test.sh\n./scripts/ui-smoke-test.sh')+'''<p>Scripts build and exercise harmless fixtures. Native render artifacts are under <code>build/ui-smoke/</code>. The UI renderer checks appearance and state behavior, not pixel equality with an approved design.</p><p>The checked-in implementation status explains the Command Line Tools adjustments and remaining release gates.</p>'''),
('unit','Required live-phase tests','''<ul><li>Malformed, oversized, null, invalid UTF-8, deeply nested, and concurrent host input.</li><li>Host output encoding and preservation of native permissions.</li><li>Path normalization, shell ambiguity, quoting, symlinks, and benign cleanup near misses.</li><li>Secrets in strings, nested objects, fragmented tokens, Unicode, logs, and errors.</li><li>Model errors, deadlines, budgets, hallucination, and evidence precedence.</li><li>Exact approval scope, expiry boundaries, replay, double-click, disconnect, restart, and simultaneous reviews.</li><li>SQLite migrations, foreign keys, permissions, retention, and transactional races.</li><li>Installer ownership, idempotency, preservation, concurrent edits, backups, and interrupted writes.</li></ul>'''),
('hosts','Prove the body never ran','''<p>Both Claude Code and Codex must exercise a real local hook on exact verified releases. A harmless denied operation in a disposable directory must leave no execution marker. Codex tests require user-reviewed trust before the callback is counted.</p><p>Review tests must cover Block, Allow once with host permissions intact, expiry denial, and an old notification. Failure tests kill the UI and service, remove the helper, disable hooks, force timeouts, and confirm honest degraded status. Privacy tests revoke keys, simulate network errors, and prove unsafe payloads are never sent.</p><p>Never use real secrets, destructive targets, or actual exfiltration as test material.</p>'''),
('corpus','The release evaluation corpus','''<p>MVP1 requires at least 40 sanitized scenarios: 10 catastrophic, 10 high-risk review, 10 benign near-misses, and 10 prompt-injection or drift cases. Each defines the gold outcome, evidence, task anchor source, and false-positive tolerance.</p><p>Version prompts and schemas, and rerun the corpus after changes. Track measured precision, missed high-risk cases, latency, calls per 100 actions, and token use. Do not publish a security efficacy percentage without measured evidence.</p>'''),
('performance','Performance targets, not promises',table(['Measure','Engineering target'],[('Ordinary local no-override, added time','MVP2 warmed-path target: p95 under 150 ms'),('Local rule decision','p95 ≤ 25 ms'),('Contextual review','8 s internal model deadline'),('High-risk approval','45 s default, within verified host timeout'),('Concurrent model reviews','Default maximum 3')])+'''<p>These targets need on-device verification and are not observed production measurements or network SLAs.</p>'''))

page('roadmap', 'MVP2 status & roadmap', 'Engineering reference', 'The completed foundation and the evidence still required for a real-protection beta.',
('status','Current implementation status',table(['Milestone','Status','Evidence / next gate'],[
('MVP1 · Native UI / Cloud Demo','Implemented; local checks passed','Native demo, sample review, 20 light/dark renders; manual accessibility and notification checks remain'),
('MVP2.0 · Baseline and contracts','Passed locally','43 tests; debug/release builds; strict v2 codec; native launch; v1 compatibility retained'),
('MVP2.1 · Service and durable state','Pending','Authenticated signed-family XPC, private hook socket, SQLite migrations, service-owned approvals and real UI state'),
('MVP2.2 · Claude Code integration','Pending','Safe configuration changes, shared emergency rules and actual Bash plus Write/Edit pre-execution deny proof'),
('MVP2.3 · Codex integration','Pending','Explicit native trust and actual Bash/apply_patch denial proof'),
('MVP2.4 · Policy and native review','Pending','Executable rule corpus, exact-invocation CAS, notification actions, expiry and replay tests'),
('MVP2.5 · Anthropic Claude BYOK','Pending','Keychain, consent, privacy preflight, real direct API call, validated verdict and incident'),
('MVP2.6 · Signed beta hardening','Pending','Developer ID, notarization, macOS 26/27, performance, accessibility and clean install/uninstall')])+'''<p>There is no released live-protection beta or signed download. Contract tests and native renders are useful development evidence; they do not prove that a real tool body was blocked.</p>'''),
('next','Next: authenticated service and storage','''<p>MVP2.1 connects the persistent service, signed UI control plane, bounded private hook transport and SQLite single writer. The native app will read sanitized service state while retaining the isolated Cloud Demo. A disconnected service must produce an honest unavailable or degraded state.</p><p>Unsigned and wrong-family clients must fail approval mutations. The hook socket must reject approval writes. Database migration, restart, retention and sanitized export checks are required. This phase can demonstrate simulated service ingestion, clearly labeled, before installing live hooks.</p><p>The <a href="/reference/docs/MVP2_PR2_PLAN.md">PR2 implementation plan</a> lists exact source changes and authentication tests.</p>'''),
('enforcement','Before protection is claimed','''<p>MVP2.2 and MVP2.3 need actual callbacks and benign denial tests on both hosts. A denied operation that would create a canary file must leave that file absent. Evidence is keyed to exact host version, adapter version, tool class, schema hash, binary signature and test time.</p><p>MVP2.4 completes deterministic critical rules and service-owned high-risk review. Block denies; Allow Once clears only TraceRook review for the original waiting invocation, with native host permissions intact. Expiry, changed arguments, changed nonces, duplicate clicks and old notifications cannot authorize another action.</p><p>MVP2.5 adds real Anthropic Claude analysis only after consent, Keychain, redaction and a second remote preflight. Model recommendations remain advisory and cannot override concrete critical evidence.</p>'''),
('release','Beta release gates','''<ul><li>Both hosts prove shell and supported file-edit pre-execution denial.</li><li>Signed app, service and CLI; authenticated IPC; no alternate approval channel.</li><li>Exact service-owned approval, bounded expiry, replay resistance and live/demo isolation.</li><li>Shared catastrophic rules work without Anthropic when the hook actually runs.</li><li>Real direct Anthropic BYOK request yields a validated, sanitized incident.</li><li>No raw commands, transcripts, keys or provider responses in persistent history or logs.</li><li>Coverage limits and host upgrades are reflected truthfully.</li><li>Clean signed/notarized install on macOS 26/27, measured latency, VoiceOver and notification checks.</li></ul><p>The <a href="/reference/docs/MVP2_ACCEPTANCE.md">phase acceptance matrix</a> keeps every release blocker explicit.</p>'''),
('observations','Actual platform and source observations','''<p>Local validation used an Apple Silicon macOS 27 host, Swift 6.4 and Command Line Tools. Full Xcode and Developer ID identities are absent. Production signed-family rejection, archive, notarization and macOS 26 validation remain open gates. The passing native SwiftPM backend emits a deprecation warning; full build-tool migration must preserve security checks.</p><p>The existing rule module contains evidence contracts rather than an executable rule engine. The foundation Codex decoder assumes object input, so live integration needs tool-specific handling. Review DTOs reuse Core’s existing ApprovalBinding rather than duplicating it in Contracts. These gaps are documented, not treated as implemented features.</p><p>Read the <a href="/reference/docs/IMPLEMENTATION_STATUS.md">implementation record</a> and <a href="/reference/docs/AGENT_COMPATIBILITY.md">compatibility audit</a> for the underlying evidence.</p>'''),
('deferred','Beyond the current beta scope','''<p>OpenCode, hosted TraceRook Cloud accounts and billing, team policy, SIEM, broad sandboxing, vulnerability scanning and system-wide monitoring are deferred. No dates or model pricing are promised.</p><p>MVP2 keeps the native macOS experience and focuses on privacy, safe configuration changes and truthful protection for supported local Claude Code and Codex sessions.</p>'''))

page('faq', 'FAQ & glossary', 'Engineering reference', 'Straight answers about Claude, local enforcement, demos, permissions, and the current preview.',
('product','Product questions','''<details open><summary>Is TraceRook ready to protect my real sessions?</summary><p>The current build includes the native UI, Cloud Demo, and tested MVP2.0 IPC contracts. Live hooks, enforcement, Anthropic BYOK, and signed beta distribution are pending. Real activity remains Not integrated.</p></details><details><summary>Why use Claude to review Claude Code or Codex?</summary><p>The coding agent and security analysis are separate roles. TraceRook uses local rules first and is designed to use Anthropic Claude to assess task relevance and suspicious context. The model is advisory; human review and deterministic policy retain authority.</p></details><details><summary>Does TraceRook replace native agent permissions?</summary><p>No. Allow once only releases TraceRook’s gate for one pending action. Native host permissions remain independently applicable.</p></details><details><summary>Is this a macOS-wide sandbox?</summary><p>No. Local hooks can only mediate supported paths where the callback actually runs and the host honors its result. Nested processes, arbitrary manual commands, and hosted or remote paths have limitations.</p></details>'''),
('privacy','Claude and privacy questions','''<details><summary>Where will my API key go?</summary><p>The planned BYOK flow stores it in macOS Keychain and sends requests directly to Anthropic. No TraceRook proxy or website key form exists. The current preview does not collect keys.</p></details><details><summary>Will entire transcripts or source trees be uploaded?</summary><p>The design uses a task anchor, a proposed action summary, selected sanitized events, and evidence. Additional code excerpts are off by default. The final privacy check must reject unsafe or uninspectable remote payloads.</p></details><details><summary>Can Claude overrule a critical local rule?</summary><p>No. Deterministic catastrophic evidence has precedence. A model-only critical verdict is capped at human review; it does not independently authorize execution or grant permission.</p></details><details><summary>Does Cloud Demo call Claude?</summary><p>No. Bundled fixtures provide the sample experience without analysis network requests. A real session must never be passed off as a cloud-analyzed fixture.</p></details>'''),
('operations','Operation questions','''<details><summary>What happens if I miss a high-risk review?</summary><p>In the intended live flow, the default 45-second deadline expires and denies the waiting high-risk call. Notification suppression does not extend the deadline. The sample flow demonstrates expiry, but real-host behavior remains a gate.</p></details><details><summary>Can a lost hook fail closed?</summary><p>Only a callback that runs and returns in time can deny. The bridge can apply local catastrophic fallback when a dependency is unavailable, but a skipped or timed-out hook cannot be forced to block by an app preference.</p></details><details><summary>Why does Codex need a trust step?</summary><p>Nonmanaged Codex hooks require review and trust of their definition. A configured hook may be skipped until trusted. TraceRook must guide the human review and verify actual execution.</p></details><details><summary>What Mac does the preview require?</summary><p>Apple Silicon, macOS 26 or later, Swift 6, and the macOS 27 SDK to build from source. Developer ID signing and notarization are required before the beta release.</p></details>'''),
('terms','Glossary',table(['Term','Meaning'],[('BYOK','Bring your own Anthropic API key; direct provider analysis'),('Task anchor','Redacted concise statement of user intent, updated by explicit user instructions'),('Pre-tool','Host lifecycle callback before a supported tool executes'),('Post-tool','Observation after a tool has executed'),('Action fingerprint','Digest of canonical original action identity for exact pending-call binding'),('Deterministic critical','Concrete catastrophic local policy evidence; not a model severity label'),('Local rules only','No contextual remote analysis; deterministic policy remains available in a live build'),('Verified coverage','Evidence that a compatible trusted callback and blocking tool path work'),('Execution unknown','Available events do not establish whether the host executed the action'),('Cloud Demo','Bundled synthetic account, analysis, and activity fixtures')]))
)
